from steps.step import Step
from utils import command
import os


class DotProfileStep(Step):
    def __init__(self, root_dir):
        super().__init__("dotprofile")
        self.root_dir = root_dir

    def _perform_impl(self):
        path = f'{os.environ["HOME"]}/.profile'
        with open(path, "w") as file:
            content = self._generate_content()
            file.write(content)

    def _generate_content(self):
        return fr"""#! usr/bin/sh
#
# This file has been autogenerated by LinuxSetup.
# Do not change it manually
#

export LINUX_SETUP_ROOT={self.root_dir}
export EDITOR=nano

source ~/Scripts/BashUtils/load_functions.sh

alias ls='ls --color=auto'

export PS1="\[\e[33m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[31m\]\h\[\e[m\]\[\e[31m\] \[\e[m\]\[\e[36m\]\w\[\e[m\]\[\e[33m\]]\[\e[m\]\[\e[31m\]\\$\[\e[m\] "

if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
    startx
fi
"""
